name: Build Win32

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: "Build  Binary"

    runs-on: windows-2019
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg-bc

    steps:
      - name: "â³ Clone repo..."
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "ğŸ–¼ï¸ Setup scene..."
        shell: bash
        run: |
          mkdir -p .vcpkg-bc
          bash ./vcpkg/bootstrap-vcpkg.sh  --disableMetrics

      - name: "ğŸ­ vcpkg: setup binary cache"
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-vcpkg-v2-${{ hashFiles('**/vcpkg.json') }}
          path: |
            .vcpkg-bc
          restore-keys: |
            ${{ runner.os }}-vcpkg-v2-
            ${{ runner.os }}-vcpkg-
            ${{ runner.os }}-

      - name: "ğŸ”§ CMake: Configure"
        run: cmake --preset win32-2019-rel

      - name: "ğŸ› ï¸ CMake: Build"
        run: cmake --build --preset win32-2019-rel

      - name: "ğŸ’£ Test um-crypto ..."
        run: ctest --output-on-failure
        working-directory: build/win32-2019-rel/um-crypto

      - name: "ğŸ“¦ Packaging"
        shell: bash
        run: |
          # build-prepared files from Win64
          mkdir -p dist
          cp build/win32-2019-rel/um-desktop/Release/um-desktop.exe \
             dist/Parakeet-win32.exe

      - name: "ğŸš€ Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: win64
          path: dist/
